'use client';

import { useCallback, useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { Loader2, Pencil, Pin, Plus, Trash2, X } from 'lucide-react';
import { adminApi } from '@/lib/api/client';
import { createNotice, deleteNotice, listAdminNotices, type NoticeDetail, type NoticeInput, updateNotice } from '@/lib/api/v1/notices';
import Alert from '@/components/ui/alert';
import Button from '@/components/ui/button';
import { useSettingsSaveRefresh } from '@/hooks/use-settings-save-refresh';

const TiptapEditor = dynamic(() => import('@/components/ui/tiptap-editor'), { ssr: false, loading: () => <div className="flex min-h-[220px] items-center justify-center"><Loader2 className="h-5 w-5 animate-spin" /></div> });
const emptyNotice = (): NoticeInput => ({ title: '', content_markdown: '', notice_type: 'system', status: 'published', is_pinned: false });

export default function AnnounceSettingsPage() {
  const refresh = useSettingsSaveRefresh();
  const [settings, setSettings] = useState<Record<string, string>>({});
  const [notices, setNotices] = useState<NoticeDetail[]>([]);
  const [draft, setDraft] = useState<NoticeInput>(emptyNotice());
  const [editing, setEditing] = useState<NoticeDetail | null>(null);
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const [values, items] = await Promise.all([adminApi.getSettings('announce'), listAdminNotices()]); setSettings(values); setNotices(items); } catch (err) { setError(err instanceof Error ? err.message : '读取失败'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const setSetting = (key: string, value: string) => setSettings((all) => ({ ...all, [key]: value }));
  const saveBanner = async () => { setSaving(true); try { await adminApi.updateSettings('announce', { announce_enabled: settings.announce_enabled || 'false', announce_content: settings.announce_content || '' }); await refresh(); setMessage('首页横幅已保存'); } catch (err) { setError(err instanceof Error ? err.message : '保存失败'); } finally { setSaving(false); } };
  const close = () => { setOpen(false); setEditing(null); setDraft(emptyNotice()); };
  const edit = (notice: NoticeDetail) => { setEditing(notice); setDraft({ title: notice.title, content_markdown: notice.content_markdown, excerpt: notice.excerpt || undefined, notice_type: notice.notice_type, status: notice.status, published_at: notice.published_at || undefined, is_pinned: notice.is_pinned }); setOpen(true); };
  const saveNotice = async () => { if (!draft.title.trim() || !draft.content_markdown.trim()) { setError('标题和正文为必填项'); return; } setSaving(true); try { const saved = editing ? await updateNotice(editing.public_id, { ...draft, change_summary: '公告内容更新' }) : await createNotice(draft); setNotices((all) => editing ? all.map((item) => item.id === saved.id ? saved : item) : [saved, ...all]); setMessage(editing ? '公告已更新' : '公告已发布'); close(); } catch (err) { setError(err instanceof Error ? err.message : '公告保存失败'); } finally { setSaving(false); } };
  const remove = async (notice: NoticeDetail) => { if (!window.confirm(`确定删除公告“${notice.title}”吗？`)) return; setSaving(true); try { await deleteNotice(notice.public_id); setNotices((all) => all.filter((item) => item.id !== notice.id)); setMessage('公告已删除'); } catch (err) { setError(err instanceof Error ? err.message : '公告删除失败'); } finally { setSaving(false); } };
  if (loading) return <div className="py-8 text-center text-surface-500">加载中...</div>;
  return <div className="border border-surface-200 bg-white"><div className="border-b border-surface-200 px-6 py-4"><h2 className="text-sm font-semibold uppercase tracking-wider text-surface-700">公告设置</h2><p className="mt-1 text-xs text-surface-400">横幅仍是站点设置；公告中心使用独立内容模型。</p></div><div className="space-y-8 p-6">{message && <Alert type="success" message={message} />}{error && <Alert type="error" message={error} />}
    <section className="space-y-4"><h3 className="text-sm font-semibold text-surface-800">首页公告横幅</h3><label className="flex gap-2 text-sm"><input type="checkbox" checked={settings.announce_enabled === 'true'} onChange={(e) => setSetting('announce_enabled', e.target.checked ? 'true' : 'false')} />启用首页公告横幅</label><textarea className="min-h-[100px] w-full rounded border border-surface-200 px-3 py-2 text-sm" value={settings.announce_content || ''} onChange={(e) => setSetting('announce_content', e.target.value)} placeholder="输入首页横幅内容（支持 Markdown）" /><Button onClick={saveBanner} disabled={saving}>保存横幅设置</Button></section>
    <section className="space-y-4 border-t border-surface-200 pt-6"><div className="flex items-start justify-between"><div><h3 className="text-sm font-semibold text-surface-800">公告中心</h3><p className="mt-1 text-xs text-surface-500">独立 ID、详情页、修订记录与客户端 API。</p></div>{!open && <Button onClick={() => { setDraft(emptyNotice()); setEditing(null); setOpen(true); }}><Plus className="mr-1.5 h-4 w-4" />发布公告</Button>}</div>
      {open && <div className="space-y-4 rounded-xl border border-surface-200 bg-surface-50 p-5"><div className="flex justify-between"><h4 className="font-semibold">{editing ? '编辑公告' : '发布公告'}</h4><button onClick={close}><X className="h-4 w-4" /></button></div><input className="w-full rounded border border-surface-200 px-3 py-2" value={draft.title} maxLength={255} onChange={(e) => setDraft((v) => ({ ...v, title: e.target.value }))} placeholder="公告标题" /><TiptapEditor value={draft.content_markdown} onChange={(content) => setDraft((v) => ({ ...v, content_markdown: content }))} minHeight="240px" imageUpload /><div className="grid gap-3 sm:grid-cols-3"><select className="rounded border border-surface-200 px-3 py-2" value={draft.notice_type} onChange={(e) => setDraft((v) => ({ ...v, notice_type: e.target.value as NoticeInput['notice_type'] }))}><option value="system">系统</option><option value="maintenance">维护</option><option value="event">活动</option><option value="policy">规则</option><option value="release">发布</option></select><select className="rounded border border-surface-200 px-3 py-2" value={draft.status} onChange={(e) => setDraft((v) => ({ ...v, status: e.target.value as NoticeInput['status'] }))}><option value="published">立即发布</option><option value="draft">草稿</option><option value="scheduled">定时发布</option><option value="archived">归档</option></select><input className="rounded border border-surface-200 px-3 py-2" type="datetime-local" value={draft.published_at ? draft.published_at.slice(0, 16) : ''} onChange={(e) => setDraft((v) => ({ ...v, published_at: e.target.value ? new Date(e.target.value).toISOString() : undefined }))} /></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={Boolean(draft.is_pinned)} onChange={(e) => setDraft((v) => ({ ...v, is_pinned: e.target.checked }))} /><Pin className="h-4 w-4" />置顶</label><div className="flex justify-end gap-2"><Button variant="ghost" onClick={close}>取消</Button><Button onClick={saveNotice} disabled={saving}>保存公告</Button></div></div>}
      <div className="space-y-3">{notices.length ? notices.map((notice) => <article key={notice.id} className="flex gap-3 rounded-xl border border-surface-200 p-4"><div className="min-w-0 flex-1"><div className="flex gap-2">{notice.is_pinned && <span className="text-xs text-amber-700">置顶</span>}<h4 className="truncate font-semibold">{notice.title}</h4><span className="text-xs text-surface-400">{notice.status}</span></div><p className="mt-2 line-clamp-2 text-sm text-surface-500">{notice.excerpt}</p></div><button onClick={() => edit(notice)} disabled={open}><Pencil className="h-4 w-4" /></button><button onClick={() => remove(notice)} disabled={open || saving} className="text-red-500"><Trash2 className="h-4 w-4" /></button></article>) : <div className="rounded-xl border border-dashed border-surface-300 px-6 py-10 text-center text-sm text-surface-500">还没有公告</div>}</div>
    </section></div></div>;
}
