/** OpenAPI shapes for the public V1 thread read and write projections. */
export const THREAD_LIST_ITEM_SCHEMA: any = {
  type: 'object',
  required: [
    'public_id', 'id', 'title', 'slug', 'status', 'is_pinned', 'is_locked', 'view_count',
    'reply_count', 'created_at', 'updated_at', 'category_id', 'user_id', 'author', 'category', 'excerpt',
  ],
  properties: {
    public_id: { type: 'string', nullable: true, example: null, description: '讨论稳定公开 ID；当前尚未分配，返回 null。' },
    id: { type: 'integer', example: 123, description: '讨论 ID。' },
    title: { type: 'string', example: '新手建筑布局分享', description: '讨论标题。' },
    slug: { type: 'string', nullable: true, example: 'xin-shou-jian-zhu', description: '标题 URL slug；可能为空。' },
    status: { type: 'string', example: 'published', description: '帖子状态。公开列表仅返回可见内容。' },
    is_pinned: { type: 'boolean', example: false, description: '是否置顶。' },
    is_locked: { type: 'boolean', example: false, description: '是否锁定，锁定后不能回复。' },
    view_count: { type: 'integer', example: 245, description: '浏览次数。' },
    reply_count: { type: 'integer', example: 8, description: '回复数量。' },
    created_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:00:00.000Z', description: '创建时间（ISO 8601）。' },
    updated_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:30:00.000Z', description: '最后更新时间（ISO 8601）。' },
    category_id: { type: 'integer', nullable: true, example: 2, description: '论坛分类 ID；未分类时为 null。' },
    user_id: { type: 'integer', example: 45, description: '作者的论坛用户 ID。' },
    author: {
      type: 'object', nullable: true, required: ['id', 'username', 'avatar_url'], description: '作者公开摘要。',
      properties: {
        id: { type: 'integer', example: 45, description: '论坛用户 ID。' },
        username: { type: 'string', example: 'builder', description: '用户名。' },
        avatar_url: { type: 'string', nullable: true, example: null, description: '头像 URL。' },
      },
    },
    category: {
      type: 'object', nullable: true, required: ['id', 'name', 'slug'], description: '分类摘要。',
      properties: {
        id: { type: 'integer', example: 2, description: '分类 ID。' },
        name: { type: 'string', example: '交流', description: '分类名称。' },
        slug: { type: 'string', nullable: true, example: 'discussion', description: '分类 URL slug。' },
      },
    },
    excerpt: { type: 'string', example: '分享一套适合新手的建筑布局……', description: '正文纯文本摘要，最多约 180 个字符。' },
  },
};

export const THREAD_CURSOR_ITEM_SCHEMA: any = {
  type: 'object',
  required: [
    'id', 'user_id', 'category_id', 'server_id', 'post_type', 'source', 'slug', 'title', 'excerpt', 'status',
    'is_pinned', 'is_locked', 'view_count', 'reply_count', 'like_count', 'created_at', 'updated_at',
    'last_activity_at', 'category_name', 'category_slug', 'category_color', 'category_icon',
    'author_mindauth_id', 'author_role', 'author_name', 'author_avatar_url', 'tags',
  ],
  properties: {
    id: { type: 'integer', example: 123, description: '讨论 ID。' },
    user_id: { type: 'integer', example: 45, description: '作者论坛用户 ID。' },
    category_id: { type: 'integer', nullable: true, example: 2, description: '分类 ID。' },
    server_id: { type: 'integer', nullable: true, example: null, description: '关联游戏服务器 ID。' },
    post_type: { type: 'string', example: 'normal', description: '帖子类型。' },
    source: { type: 'string', example: 'USER', description: '帖子来源。' },
    slug: { type: 'string', nullable: true, example: 'xin-shou-jian-zhu', description: '标题 URL slug。' },
    title: { type: 'string', example: '新手建筑布局分享', description: '讨论标题。' },
    excerpt: { type: 'string', example: '分享一套适合新手的建筑布局……', description: '纯文本摘要。' },
    status: { type: 'string', example: 'published', description: '帖子状态。' },
    is_pinned: { type: 'boolean', example: false, description: '是否置顶。' },
    is_locked: { type: 'boolean', example: false, description: '是否锁定。' },
    view_count: { type: 'integer', example: 245, description: '浏览次数。' },
    reply_count: { type: 'integer', example: 8, description: '回复数量。' },
    like_count: { type: 'integer', example: 12, description: '点赞数。' },
    created_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:00:00.000Z', description: '创建时间。' },
    updated_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:30:00.000Z', description: '最后更新时间。' },
    last_activity_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:30:00.000Z', description: '最近活动时间。' },
    category_name: { type: 'string', nullable: true, example: '交流', description: '分类名称。' },
    category_slug: { type: 'string', nullable: true, example: 'discussion', description: '分类 URL slug。' },
    category_color: { type: 'string', nullable: true, example: '#336699', description: '分类主题色。' },
    category_icon: { type: 'string', nullable: true, example: 'chat', description: '分类图标标识。' },
    author_mindauth_id: { type: 'integer', nullable: true, example: 789, description: 'MindAuth 账号 ID。' },
    author_role: { type: 'string', nullable: true, example: 'user', description: '作者论坛角色。' },
    author_name: { type: 'string', nullable: true, example: 'builder', description: '作者用户名。' },
    author_avatar_url: { type: 'string', nullable: true, example: null, description: '作者头像 URL。' },
    tags: { type: 'array', description: '帖子标签。', items: { type: 'object', required: ['id', 'name', 'slug', 'created_at'], properties: {
      id: { type: 'integer', example: 7, description: '标签 ID。' },
      name: { type: 'string', example: '建筑', description: '标签名称。' },
      slug: { type: 'string', example: 'jian-zhu', description: '标签 URL slug。' },
      created_at: { type: 'string', format: 'date-time', example: '2026-09-01T00:00:00.000Z', description: '标签创建时间。' },
    } } },
  },
};

export const THREAD_REPLY_SCHEMA: any = {
  type: 'object',
  required: [
    'id', 'post_id', 'user_id', 'parent_reply_id', 'content', 'content_format', 'content_html',
    'content_json', 'content_schema_version', 'content_text', 'status', 'like_count', 'created_at',
    'updated_at', 'author_mindauth_id', 'author_role', 'author_name', 'author_avatar_url', 'location_label',
  ],
  properties: {
    child_count: { type: 'integer', minimum: 0, description: '直接子回复数；通过子回复分页接口展开。' },
    id: { type: 'integer', example: 456, description: '回复 ID。' },
    post_id: { type: 'integer', example: 123, description: '所属讨论 ID。' },
    user_id: { type: 'integer', example: 45, description: '作者的论坛用户 ID。' },
    parent_reply_id: { type: 'integer', nullable: true, example: null, description: '父回复 ID；直接回复讨论时为 null。' },
    content: { type: 'string', example: '可以试试把电力区放在地图中央。', description: '纯文本兼容正文。' },
    content_format: { type: 'string', enum: ['tiptap_json'], example: 'tiptap_json', description: '正文规范。' },
    content_html: { type: 'string', nullable: true, example: '<p>可以试试把电力区放在地图中央。</p>', description: '服务端生成的安全 HTML。' },
    content_json: { type: 'object', nullable: true, example: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: '可以试试把电力区放在地图中央。' }] }] }, description: 'Rich Content Schema v2 文档。' },
    content_schema_version: { type: 'integer', example: 2, description: 'content_json 的 Schema 版本。' },
    content_text: { type: 'string', nullable: true, example: '可以试试把电力区放在地图中央。', description: '供搜索和纯文本客户端使用的正文投影。' },
    status: { type: 'string', example: 'published', description: '回复状态。' },
    like_count: { type: 'integer', example: 3, description: '点赞数。' },
    created_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:30:00.000Z', description: '创建时间（ISO 8601）。' },
    updated_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:30:00.000Z', description: '最后更新时间（ISO 8601）。' },
    author_mindauth_id: { type: 'integer', nullable: true, example: 789, description: 'MindAuth 账号 ID。' },
    author_role: { type: 'string', nullable: true, example: 'user', description: '论坛角色。' },
    author_name: { type: 'string', nullable: true, example: 'builder', description: '作者用户名。' },
    author_avatar_url: { type: 'string', nullable: true, example: null, description: '作者头像 URL。' },
    location_label: { type: 'string', nullable: true, example: null, description: '作者发布时的地区标签。' },
  },
};

export const THREAD_DETAIL_SCHEMA: any = {
  ...THREAD_LIST_ITEM_SCHEMA,
  required: [
    ...THREAD_LIST_ITEM_SCHEMA.required,
    'content', 'content_format', 'content_html', 'content_json', 'content_schema_version', 'content_text',
    'server_id', 'required_group_id', 'post_type', 'best_reply_id', 'edited_at', 'like_count',
    'category_name', 'category_slug', 'category_color', 'category_icon', 'author_mindauth_id',
    'author_role', 'author_name', 'author_avatar_url', 'location_label', 'prefix', 'tags', 'viewer',
    'is_owner', 'replies', 'reply_pagination',
  ],
  properties: {
    ...THREAD_LIST_ITEM_SCHEMA.properties,
    content: { type: 'string', example: '分享一套适合新手的建筑布局。', description: '纯文本兼容正文。' },
    content_format: { type: 'string', enum: ['tiptap_json'], example: 'tiptap_json', description: '正文规范。' },
    content_html: { type: 'string', nullable: true, example: '<p>分享一套适合新手的建筑布局。</p>', description: '服务端生成的安全 HTML。' },
    content_json: { type: 'object', nullable: true, example: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: '分享一套适合新手的建筑布局。' }] }] }, description: 'Rich Content Schema v2 文档。' },
    content_schema_version: { type: 'integer', example: 2, description: 'content_json 的 Schema 版本。' },
    content_text: { type: 'string', nullable: true, example: '分享一套适合新手的建筑布局。', description: '供搜索和纯文本客户端使用的正文投影。' },
    server_id: { type: 'integer', nullable: true, example: null, description: '关联游戏服务器 ID。' },
    required_group_id: { type: 'integer', nullable: true, example: null, description: '可见用户组限制；无额外限制时为 null。' },
    post_type: { type: 'string', example: 'normal', description: '帖子类型。' },
    best_reply_id: { type: 'integer', nullable: true, example: null, description: '被标记为最佳答案的回复 ID。' },
    edited_at: { type: 'string', format: 'date-time', nullable: true, example: null, description: '最后编辑时间；未编辑时为 null。' },
    like_count: { type: 'integer', example: 12, description: '点赞数。' },
    category_name: { type: 'string', nullable: true, example: '交流', description: '分类名称。' },
    category_slug: { type: 'string', nullable: true, example: 'discussion', description: '分类 URL slug。' },
    category_color: { type: 'string', nullable: true, example: '#336699', description: '分类主题色。' },
    category_icon: { type: 'string', nullable: true, example: 'chat', description: '分类图标标识。' },
    author_mindauth_id: { type: 'integer', nullable: true, example: 789, description: 'MindAuth 账号 ID。' },
    author_role: { type: 'string', nullable: true, example: 'user', description: '作者论坛角色。' },
    author_name: { type: 'string', nullable: true, example: 'builder', description: '作者用户名。' },
    author_avatar_url: { type: 'string', nullable: true, example: null, description: '作者头像 URL。' },
    location_label: { type: 'string', nullable: true, example: null, description: '作者发布时的地区标签。' },
    prefix: {
      type: 'object', nullable: true, required: ['value', 'label', 'color'], description: '非普通帖子类型对应的前缀信息。',
      properties: {
        value: { type: 'string', example: 'help', description: '前缀标识。' },
        label: { type: 'string', example: '求助', description: '前缀显示名。' },
        color: { type: 'string', example: '#336699', description: '前缀颜色。' },
      },
    },
    tags: {
      type: 'array', description: '帖子标签。',
      items: { type: 'object', required: ['id', 'name', 'slug', 'created_at'], properties: {
        id: { type: 'integer', example: 7, description: '标签 ID。' },
        name: { type: 'string', example: '建筑', description: '标签名称。' },
        slug: { type: 'string', example: 'jian-zhu', description: '标签 URL slug。' },
        created_at: { type: 'string', format: 'date-time', example: '2026-09-01T00:00:00.000Z', description: '标签创建时间。' },
      } },
    },
    viewer: { type: 'object', nullable: true, required: ['liked', 'bookmarked'], description: '当前登录用户对本帖的状态；匿名时为 null。', properties: {
      liked: { type: 'boolean', example: false, description: '当前用户是否已点赞。' },
      bookmarked: { type: 'boolean', example: false, description: '当前用户是否已收藏。' },
    } },
    is_owner: { type: 'boolean', example: false, description: '当前用户是否为帖子作者。' },
    replies: { type: 'array', description: '详情附带的首批回复；继续翻页请使用独立回复列表接口。', items: {
      ...THREAD_REPLY_SCHEMA,
      properties: { ...THREAD_REPLY_SCHEMA.properties, is_owner: { type: 'boolean', example: false, description: '当前用户是否为回复作者。' } },
      required: [...THREAD_REPLY_SCHEMA.required, 'is_owner'],
    } },
    reply_pagination: { type: 'object', required: ['total', 'page', 'limit', 'total_pages'], description: '详情内回复页信息。', properties: {
      total: { type: 'integer', example: 8, description: '回复总数。' },
      page: { type: 'integer', example: 1, description: '当前页。' },
      limit: { type: 'integer', example: 50, description: '每页条数。' },
      total_pages: { type: 'integer', example: 1, description: '总页数。' },
    } },
  },
};

export const THREAD_WRITE_SCHEMA: any = {
  type: 'object',
  required: ['id', 'public_id', 'title', 'content', 'content_format', 'content_schema_version', 'content_html', 'content_json', 'content_text', 'status', 'created_at', 'updated_at'],
  properties: {
    id: { type: 'integer', example: 123, description: '新建或更新后的讨论 ID。' },
    public_id: { type: 'string', nullable: true, example: null, description: '当前未分配的讨论稳定公开 ID。' },
    title: { type: 'string', example: '新手建筑布局分享', description: '讨论标题。' },
    content: { type: 'string', example: '分享一套适合新手的建筑布局。', description: '纯文本兼容正文。' },
    content_format: { type: 'string', enum: ['tiptap_json'], example: 'tiptap_json', description: '正文规范。' },
    content_schema_version: { type: 'integer', example: 2, description: '富文本 Schema 版本。' },
    content_html: { type: 'string', nullable: true, example: '<p>分享一套适合新手的建筑布局。</p>', description: '服务端生成的安全 HTML。' },
    content_json: { type: 'object', nullable: true, example: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: '分享一套适合新手的建筑布局。' }] }] }, description: 'Rich Content Schema v2 文档。' },
    content_text: { type: 'string', nullable: true, example: '分享一套适合新手的建筑布局。', description: '供搜索和纯文本客户端使用的正文投影。' },
    status: { type: 'string', example: 'pending', description: '服务端实际保存状态，可能进入审核队列。' },
    created_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:00:00.000Z', description: '创建时间。' },
    updated_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:00:00.000Z', description: '最后更新时间。' },
  },
};

export const REPLY_WRITE_SCHEMA: any = {
  type: 'object',
  required: ['id', 'post_id', 'parent_reply_id', 'content', 'content_format', 'content_schema_version', 'content_html', 'content_json', 'content_text', 'status', 'created_at', 'updated_at'],
  properties: {
    id: { type: 'integer', example: 456, description: '新建或更新后的回复 ID。' },
    post_id: { type: 'integer', example: 123, description: '所属讨论 ID。' },
    parent_reply_id: { type: 'integer', nullable: true, example: null, description: '父回复 ID；直接回复讨论时为 null。' },
    content: { type: 'string', example: '可以试试把电力区放在地图中央。', description: '纯文本兼容正文。' },
    content_format: { type: 'string', enum: ['tiptap_json'], example: 'tiptap_json', description: '正文规范。' },
    content_schema_version: { type: 'integer', example: 2, description: '富文本 Schema 版本。' },
    content_html: { type: 'string', nullable: true, example: '<p>可以试试把电力区放在地图中央。</p>', description: '服务端生成的安全 HTML。' },
    content_json: { type: 'object', nullable: true, example: { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: '可以试试把电力区放在地图中央。' }] }] }, description: 'Rich Content Schema v2 文档。' },
    content_text: { type: 'string', nullable: true, example: '可以试试把电力区放在地图中央。', description: '供搜索和纯文本客户端使用的正文投影。' },
    status: { type: 'string', example: 'pending', description: '服务端实际保存状态，可能进入审核队列。' },
    created_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:30:00.000Z', description: '创建时间。' },
    updated_at: { type: 'string', format: 'date-time', example: '2026-09-30T12:30:00.000Z', description: '最后更新时间。' },
  },
};
